### ISSUE TITLE
Stop creating vm with same name

### ISSUE THREAD

**Issue by sp-yduck** [k8s-proxmox/cluster-api-provider-proxmox#147] opened 2023-11-19 07:18 UTC
> ![5EAA7C85-ADAA-4A86-80C2-46BE8B3FF9B6_1_201_a](https://github.com/sp-yduck/cluster-api-provider-proxmox/assets/114269969/9509bc2c-89af-43d0-a8c8-48ff616bf4f4)
from this picture, It succeed in authentication. But the VM created too much. Is it natural for using Cluster-API?

_Originally posted by @Rwatana in https://github.com/sp-yduck/cluster-api-provider-proxmox/issues/109#issuecomment-1817346374_
            

this happens when cappx successfully creates vm but fails to confirm if the vm is actually created. in the controller loop, cappx shoud check if there is already vm with same name to avoid creating new vm with same name(spec)

**Comment by Rwatana** [comment] 2023-11-25 03:38
## Topic

By changing the time in previous issue, I could manage to access workload cluster.
But while scaling up, the same name vm created more and more.
I think the problem is resolved by changing to time from 10 sec to 60 sec.
In my environment, Do I have to set the replicas to 1?

## My try
I try to modify and add the parts to wait. But the problem remains.
```
func (s *Service) MustGetTask(ctx context.Context, node string, upid string) (*api.Task, error) {
	time.Sleep(time.Second * 60)
	for i := 0; i < 40; i++ {
		task, err := s.restclient.GetTask(ctx, node, upid)
		if err != nil {
			if rest.IsNotFound(err) {
				time.Sleep(time.Second * 1)
				continue
			}
			return nil, err
		}
		return task, nil
	}
	return nil, errors.New("task wait deadline exceeded")
}
```

## Log
```
root@Copy-of-VM-9000:~# clusterctl describe cluster cappx-test
NAME                                                                        READY  SEVERITY  REASON                    SINCE  MESSAGE
Cluster/cappx-test                                                          False  Warning   ScalingUp                 37m    Scaling up control plane to 3 replicas (actual 1)
├─ClusterInfrastructure - ProxmoxCluster/cappx-test
└─ControlPlane - KubeadmControlPlane/cappx-test                             False  Warning   ScalingUp                 37m    Scaling up control plane to 3 replicas (actual 1)
  ├─Machine/cappx-test-2xtpb                                                True                                       37m
  │ └─MachineInfrastructure - ProxmoxMachine/cappx-test-controlplane-qsbwt
  └─Machine/cappx-test-dphbf                                                False  Info      WaitingForInfrastructure  22s    1 of 2 completed
    └─MachineInfrastructure - ProxmoxMachine/cappx-test-controlplane-6kxkm
```

**Comment by sp-yduck** [comment] 2023-11-25 07:19
Could you check how long your host machine takes for creating qemu ? you can check the duration from Task's Status 

![qemu_task_duration](https://github.com/sp-yduck/cluster-api-provider-proxmox/assets/63634867/82081e2e-452a-457d-b316-65a8b5e9e758)

**Closed** 2023-12-06 10:56 UTC
